// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAECZs5V-hxH8VJ-Nsp7kPMQhLQeVA11A8',
    appId: '1:829403222244:web:ed22c066f2b8fb6c861cf1',
    messagingSenderId: '829403222244',
    projectId: 'tomatotime-7a551',
    authDomain: 'tomatotime-7a551.firebaseapp.com',
    storageBucket: 'tomatotime-7a551.firebasestorage.app',
    measurementId: 'G-X5V49BFD3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJHOjtuVPzDEjvgLQFsTtb_U8Gs5Yac48',
    appId: '1:829403222244:android:a05389c5959c54be861cf1',
    messagingSenderId: '829403222244',
    projectId: 'tomatotime-7a551',
    storageBucket: 'tomatotime-7a551.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP6tHBt0dwi7hEe3bN_o38NDwLsHneCv4',
    appId: '1:829403222244:ios:c7bc7ecbf25f5f03861cf1',
    messagingSenderId: '829403222244',
    projectId: 'tomatotime-7a551',
    storageBucket: 'tomatotime-7a551.firebasestorage.app',
    iosBundleId: 'com.example.tomatoTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAECZs5V-hxH8VJ-Nsp7kPMQhLQeVA11A8',
    appId: '1:829403222244:web:244b69d548c6a387861cf1',
    messagingSenderId: '829403222244',
    projectId: 'tomatotime-7a551',
    authDomain: 'tomatotime-7a551.firebaseapp.com',
    storageBucket: 'tomatotime-7a551.firebasestorage.app',
    measurementId: 'G-FJYPW6W6LD',
  );
}
